### ISSUE TITLE
Subgraph: ContributionSent() event could be improved

### ISSUE THREAD

**Issue by daodesigner** [quadratic-funding/qfi#34]
Investigate if the voice credits amount is redundant (also the SignUp() event has some VCs data emitted) and can be removed.

**Comment by Jeeiii** [comment]
We could leverage the `voiceCreditBalance` computation from the _`signUp()`_ method as long as we do not have any top-ups feature on QFI (just because each top up after the first one would not invoke the _`signUp()`_ method, so no override on the `PublicKey` `voiceCreditBalance` field on the subgraph will happen in this case).
